// gen-identos — generate the frozen Idento pool (src/lib/p2p/Identos.ts).
//  A fat pre-generated pool of identities the flock draws from round-robin: each Story
//   run takes the next slice so consecutive runs never reuse a prepub (PeerJS AND the
//    relay ARP both refuse a name already claimed). Deterministic — each identity is
//     derived from the seed `jamsend-pool-<i>` exactly as Idento.generateKeys(seed) does
//      (SHA-256 of the seed → ed25519 private key → public key), so the pool, and thus
//       every snap that names a peer, stays stable across regenerations. Reviewable +
//        regenerable: `npx vite-node -c scripts/compile.vite.config.ts scripts/gen-identos.ts`.
import * as ed from '@noble/ed25519'
import { writeFile } from 'node:fs/promises'

const enhex = ed.etc.bytesToHex
const N = 64

// mirror Idento.generateKeys(seed:string): hash the seed to a 32-byte private key.
async function deriveKey(seed: string): Promise<Uint8Array> {
	const data = new TextEncoder().encode(seed)
	const hash = await crypto.subtle.digest('SHA-256', data)
	return new Uint8Array(hash)
}

const rows: string[] = []
for (let i = 0; i < N; i++) {
	const friendly = 'peer' + String(i).padStart(2, '0')
	const priv = await deriveKey(`jamsend-pool-${i}`)
	const pub = await ed.getPublicKeyAsync(priv)
	const pubhex = enhex(pub)
	const prepub = pubhex.slice(0, 16) // pretty_pubkey(): the 16-hex name/address
	rows.push(`\t{ prepub: "${prepub}", friendly: "${friendly}", pub: "${pubhex}", key: "${enhex(priv)}" },`)
}

const module = `// GENERATED by scripts/gen-identos.ts — do not edit by hand; regen with
//  \`npx vite-node scripts/gen-identos.ts\`.
//
//  The frozen Idento pool the peer flock draws from. Each Story run cycles a round-robin
//   cursor through this pool (Identos_draw), so consecutive runs claim FRESH prepubs and
//    never collide on a name PeerJS / the relay ARP still has registered from the last
//     run. \`prepub\` (Idento.pretty_pubkey(), 16 hex) is the peer's name AND its routing
//      address (header.to); \`friendly\` is a readable label for snaps/logs; \`pub\`/\`key\` are
//       the full ed25519 keypair (storableIdento), thawable via new Idento().thaw({pub,key}).
//        Deterministic from seed \`jamsend-pool-<i>\` so the pool — and snap peer-names — are stable.
export type FrozenIdento = { prepub: string; friendly: string; pub: string; key: string }

export const IDENTO_POOL: FrozenIdento[] = [
${rows.join('\n')}
]
`

await writeFile('src/lib/p2p/Identos.ts', module)
console.log(`gen-identos: wrote ${N} identos → src/lib/p2p/Identos.ts`)
