// gen-cluster-identos — mint the SECRET cluster Idento flock → .env.cluster-identos
//
//  Sibling of gen-identos.ts, but the opposite trust posture. gen-identos makes a PUBLIC,
//   deterministic pool (seed `jamsend-pool-<i>`) committed as src/lib/p2p/Identos.ts — stable
//    peer NAMES, no secrecy. THIS makes the cluster's TRUST ANCHORS: one random ed25519 keypair
//     per role (editor/runner/claude/…), written to a gitignored .env so the private keys never
//      enter the repo or the wire. Privileged frames (gen_write, dock_push) are signed by one of
//       these; a receiver verifies header_sign against the flock's PUBLIC keys (CLUSTER_TRUSTED_PUBS)
//        and drops anything unsigned/foreign — closing the unauthenticated-relay RCE (anyone who can
//         reach the relay today can gen_write arbitrary code to disk and Vite runs it).
//
//  Keys are RANDOM, not seeded: a public seed would let anyone regenerate the "secret". So a re-run
//   ROTATES the whole flock — guarded behind --force so you don't silently break a live cluster.
//
//  Run:  npx vite-node -c scripts/compile.vite.config.ts scripts/gen-cluster-identos.ts [roles...] [--force]
//        (default roles: editor runner claude)
//  Then: add `- .env.cluster-identos` to each machine's docker-compose env_file, and distribute the
//        file out-of-band to the trusted hosts (it is gitignored — never commit it).
import * as ed from '@noble/ed25519'
import { writeFile, access } from 'node:fs/promises'

const enhex = ed.etc.bytesToHex
const OUT = '.env.cluster-identos'

const argv  = process.argv.slice(2)
const force = argv.includes('--force')
const roles = argv.filter(a => !a.startsWith('-'))
if (!roles.length) roles.push('editor', 'runner', 'claude')

// Refuse to clobber an existing flock unless --force: re-minting rotates every key and breaks
//  any peer still holding the old set. Rotation should be deliberate.
const exists = await access(OUT).then(() => true, () => false)
if (exists && !force) {
	console.error(`✗ ${OUT} already exists — re-running ROTATES every cluster key and breaks live peers.`)
	console.error(`  Pass --force to rotate deliberately.`)
	process.exit(1)
}

type Minted = { role: string; pub: string; prepub: string; key: string }
const minted: Minted[] = []
for (const role of roles) {
	const priv = ed.utils.randomPrivateKey()          // RANDOM — not a public seed
	const pub  = await ed.getPublicKeyAsync(priv)
	const pubhex = enhex(pub)
	minted.push({ role, pub: pubhex, prepub: pubhex.slice(0, 16), key: enhex(priv) })
}

// The flock's public keys — what every verifier loads to decide "is this signer one of ours?".
//  Full 64-hex pubs; the 16-hex prepub (header.from / routing addr) is derived from each.
const trusted = minted.map(m => m.pub).join(',')

const ROLE_ENV = (r: string) => r.toUpperCase().replace(/[^A-Z0-9]/g, '_')
const lines = [
	`# GENERATED by scripts/gen-cluster-identos.ts — SECRET. Gitignored (.env.*). Never commit.`,
	`# Distribute out-of-band to trusted hosts; add to each docker-compose env_file.`,
	`# Re-mint with --force to ROTATE (breaks peers holding the old keys).`,
	``,
	`# Every verifier loads this: the flock's public keys. A header_sign by any of these is trusted.`,
	`CLUSTER_TRUSTED_PUBS=${trusted}`,
	``,
	`# Per-role keypair. A process picks its own role's KEY to SIGN; PUB is informational.`,
	...minted.flatMap(m => [
		`# ${m.role}  (prepub/addr ${m.prepub})`,
		`CLUSTER_IDENTO_${ROLE_ENV(m.role)}_PUB=${m.pub}`,
		`CLUSTER_IDENTO_${ROLE_ENV(m.role)}_KEY=${m.key}`,
	]),
	``,
]

await writeFile(OUT, lines.join('\n'))
console.log(`gen-cluster-identos: minted ${minted.length} role key(s) → ${OUT}${exists ? ' (ROTATED)' : ''}`)
for (const m of minted) console.log(`  ${m.role.padEnd(8)} addr ${m.prepub}  pub ${m.pub.slice(0, 24)}…`)
console.log(`\n⚠ SECRET — gitignored; distribute out-of-band, add to docker-compose env_file.`)
