// gen-cluster-identos — mint the SECRET cluster Idento flock, SPLIT per role so no host or
//  container ever holds a secret it doesn't own.
//
//  Sibling of gen-identos.ts but the opposite trust posture. gen-identos makes a PUBLIC,
//   deterministic pool (committed). THIS makes the cluster's TRUST ANCHORS: one random ed25519
//    keypair per role (editor/runner/claude/…). Privileged frames (gen_write, this_dock_updated)
//     are signed by one of these; a receiver verifies against the flock's PUBLIC keys and drops
//      anything unsigned/foreign — closing the unauthenticated-relay RCE.
//
//  Output is SPLIT (the over-share fix): each file is gitignored (.env.*).
//   - .env.cluster-pubs        PUBLIC — CLUSTER_TRUSTED_PUBS (every verifier's env_file: the relay,
//                               and vite bakes it to VITE_CLUSTER_TRUSTED_PUBS for the browser).
//   - .env.cluster-<role>      SECRET — that role's CLUSTER_IDENTO_<ROLE>_KEY/_PUB. Distribute ONLY
//                               to that role's host; env_file it into ONLY that service. So a
//                                container never loads (env_file) NOR can read (a single combined
//                                 file under .:/app) another role's private key.
//  Keys are RANDOM, not seeded (a public seed = no secret). A re-run ROTATES — guarded by --force.
//
//  Run:  npx vite-node -c scripts/compile.vite.config.ts scripts/gen-cluster-identos.ts [roles...] [--force]
//        (default roles: editor runner claude)
import * as ed from '@noble/ed25519'
import { writeFile, access } from 'node:fs/promises'

const enhex = ed.etc.bytesToHex

const argv  = process.argv.slice(2)
const force = argv.includes('--force')
const roles = argv.filter(a => !a.startsWith('-'))
if (!roles.length) roles.push('editor', 'runner', 'claude')

const ROLE_ENV = (r: string) => r.toUpperCase().replace(/[^A-Z0-9]/g, '_')
const pubsFile = '.env.cluster-pubs'
const roleFile = (r: string) => `.env.cluster-${r}`
const files = [pubsFile, ...roles.map(roleFile)]

// Refuse to clobber any existing flock file unless --force: re-minting rotates every key and
//  breaks peers holding the old set. Rotation should be deliberate.
for (const f of files) {
	if (await access(f).then(() => true, () => false) && !force) {
		console.error(`✗ ${f} already exists — re-running ROTATES every cluster key and breaks live peers.`)
		console.error(`  Pass --force to rotate deliberately.`)
		process.exit(1)
	}
}

type Minted = { role: string; pub: string; prepub: string; key: string }
const minted: Minted[] = []
for (const role of roles) {
	const priv = ed.utils.randomPrivateKey()          // RANDOM — not a public seed
	const pub  = await ed.getPublicKeyAsync(priv)
	const pubhex = enhex(pub)
	minted.push({ role, pub: pubhex, prepub: pubhex.slice(0, 16), key: enhex(priv) })
}

const head = (extra: string) =>
	`# GENERATED by scripts/gen-cluster-identos.ts — gitignored (.env.*). ${extra}\n`

// PUBLIC pubs — every verifier loads this; safe to share. A header_sign by any of these is trusted.
//  Also carries EDITOR_URL: where clients (ghost-update) reach the editor's relay/server to notify +
//   verify. Defaults to the docker-bridge :9092 staging editor; override per deployment.
await writeFile(pubsFile, head('PUBLIC: the flock\'s public keys + the editor URL. Distribute everywhere.')
	+ `CLUSTER_TRUSTED_PUBS=${minted.map(m => m.pub).join(',')}\n`
	+ `EDITOR_URL=http://172.17.0.1:9092\n`)

// One SECRET file per role — distribute ONLY to that role's host; env_file into ONLY that service.
for (const m of minted) {
	await writeFile(roleFile(m.role), head(`SECRET — ${m.role} only (addr ${m.prepub}). Distribute to the ${m.role} host alone; never to another container.`)
		+ `CLUSTER_IDENTO_${ROLE_ENV(m.role)}_KEY=${m.key}\n`
		+ `CLUSTER_IDENTO_${ROLE_ENV(m.role)}_PUB=${m.pub}\n`)
}

console.log(`gen-cluster-identos: minted ${minted.length} role(s), split across ${files.length} files${force ? ' (ROTATED)' : ''}`)
console.log(`  ${pubsFile}  (PUBLIC — every verifier)`)
for (const m of minted) console.log(`  ${roleFile(m.role).padEnd(22)} (SECRET — ${m.role} host only, addr ${m.prepub})`)
console.log(`\n⚠ Distribute each .env.cluster-<role> to that role's host ALONE; env_file it into only that`)
console.log(`  service. Keep .env.cluster-pubs everywhere. Don't leave foreign role files on a host.`)

// A browser editor/runner can't read these node-side env files — it gets its key from localStorage.
//  Rather than hand-craft JSON, copy a role file to the clipboard and paste it into the app's Id hatch
//   (the 'Id' action button → paste box), which parses this .env format and stores the keypair.
console.log(`\nTo load a BROWSER tab's identity: copy its role file, then paste into the app's Id hatch`)
console.log(`  ('Id' action button → paste box — it parses this .env format):`)
for (const m of minted) console.log(`    ${(m.role + ':').padEnd(8)} cat ${roleFile(m.role)} | xclip -selection clipboard`)
