// mint-cluster-cert — the TYRANT's pen. Two jobs (Cluster_spec §2.8):
//
//   new-tyrant   mint the root keypair: a SECRET .env.cluster-tyrant (the tyrant's signing key,
//                 staging-box only) + the PUBLIC CLUSTER_TYRANT_PUB line to paste into
//                  .env.cluster-pubs (every verifier bakes it; checking is offline against it).
//   grant        sign a capability cert delegating `can:` to a grantee pub, one hop deep. Print the
//                 cert JSON to paste into a %Trust particle / a runner's env / the Id hatch.
//
//  The tyrant is contacted ONLY here, to MINT. No peer ever calls it to CHECK — verifyCert/
//   resolveCapability (cluster_trust.ts) resolve a presented cert offline against the public root.
//    The tyrant KEY stays on the tyrant host alone (.env.cluster-tyrant is gitignored, .env.*).
//
//  Run:  vite-node -c scripts/compile.vite.config.ts scripts/mint-cluster-cert.ts new-tyrant [--force]
//        vite-node -c scripts/compile.vite.config.ts scripts/mint-cluster-cert.ts grant \
//                    --grantee <64-hex pub> --can run-code,restart [--days 90] [--note "runnerA"] [--out cert.json]
import * as ed from '@noble/ed25519'
import { writeFile, readFile, access } from 'node:fs/promises'
import { mintCert, prepubOf, type Capability } from '../src/lib/p2p/cluster_trust'

const enhex = ed.etc.bytesToHex
const TYRANT_FILE = '.env.cluster-tyrant'

const argv = process.argv.slice(2)
const cmd = argv[0]
function flag(name: string): string | undefined {
	const i = argv.indexOf(`--${name}`)
	return i >= 0 ? argv[i + 1] : undefined
}
const has = (name: string) => argv.includes(`--${name}`)

// Parse a KEY=value .env file into a map (ignores comments/blanks). Used to load the tyrant key
//  from .env.cluster-tyrant when it isn't already in the process env.
async function readEnvFile(path: string): Promise<Record<string, string>> {
	const out: Record<string, string> = {}
	try {
		const text = await readFile(path, 'utf8')
		for (const line of text.split('\n')) {
			const t = line.trim()
			if (!t || t.startsWith('#')) continue
			const eq = t.indexOf('=')
			if (eq > 0) out[t.slice(0, eq).trim()] = t.slice(eq + 1).trim()
		}
	} catch { /* absent — caller decides if that's fatal */ }
	return out
}

async function newTyrant() {
	if (await access(TYRANT_FILE).then(() => true, () => false) && !has('force')) {
		console.error(`✗ ${TYRANT_FILE} already exists — re-minting ROTATES the root and INVALIDATES every cert.`)
		console.error(`  Pass --force to rotate the tyrant deliberately (then re-grant all certs).`)
		process.exit(1)
	}
	const priv = ed.utils.randomPrivateKey()
	const pub = enhex(await ed.getPublicKeyAsync(priv))
	await writeFile(TYRANT_FILE,
		`# GENERATED by scripts/mint-cluster-cert.ts — SECRET tyrant root key. gitignored (.env.*).\n`
		+ `#  Keep on the tyrant host ALONE (staging). Never env_file it into a runner/relay container.\n`
		+ `CLUSTER_IDENTO_TYRANT_KEY=${enhex(priv)}\n`
		+ `CLUSTER_TYRANT_PUB=${pub}\n`)
	console.log(`✓ minted tyrant root (addr ${prepubOf(pub)}) → ${TYRANT_FILE} (SECRET — staging only)`)
	console.log(`\nAdd this PUBLIC line to .env.cluster-pubs (every verifier bakes it; vite → VITE_CLUSTER_TYRANT_PUB):`)
	console.log(`  CLUSTER_TYRANT_PUB=${pub}`)
}

async function grant() {
	const grantee = flag('grantee')
	if (!grantee || !/^[0-9a-f]{64}$/i.test(grantee)) {
		console.error('✗ --grantee <64-hex pub> required (the full public key the cert is granted TO)')
		process.exit(1)
	}
	const can = (flag('can') ?? 'run-code').split(',').map(s => s.trim()).filter(Boolean) as Capability[]
	const days = flag('days') ? Number(flag('days')) : undefined
	const note = flag('note')
	// Tyrant key: process env first (env_file'd .env.cluster-tyrant), else read the file directly.
	const tyrantKey = process.env.CLUSTER_IDENTO_TYRANT_KEY
		?? (await readEnvFile(TYRANT_FILE)).CLUSTER_IDENTO_TYRANT_KEY
	if (!tyrantKey) {
		console.error(`✗ no tyrant key — set CLUSTER_IDENTO_TYRANT_KEY or run 'new-tyrant' to mint ${TYRANT_FILE} first.`)
		process.exit(1)
	}
	const now = Date.now()
	const cert = await mintCert({
		grantee,
		can,
		...(days ? { not_after: now + days * 86_400_000 } : {}),
		...(note ? { note } : {}),
	}, tyrantKey, now)
	const json = JSON.stringify(cert, null, 2)
	const out = flag('out')
	if (out) { await writeFile(out, json + '\n'); console.log(`✓ cert → ${out}`) }
	console.log(`✓ granted [${can.join(', ')}] to ${prepubOf(grantee)}${days ? ` (expires in ${days}d)` : ' (no expiry)'}`)
	console.log(`\n${json}`)
	console.log(`\nPaste into a %Trust particle / a runner's env / the Id hatch. It resolves OFFLINE against`)
	console.log(`  CLUSTER_TYRANT_PUB — the tyrant is never contacted to check it.`)
}

async function main() {
	if (cmd === 'new-tyrant') await newTyrant()
	else if (cmd === 'grant') await grant()
	else {
		console.error('usage: mint-cluster-cert.ts new-tyrant [--force]')
		console.error('       mint-cluster-cert.ts grant --grantee <pub> --can run-code,restart [--days N] [--note "..."] [--out cert.json]')
		process.exit(1)
	}
}
main().catch((e) => { console.error('mint-cluster-cert threw:', e); process.exit(1) })
