// vyto_search_sample.mjs — real code-search result sets for the Vyto glass to be designed against.
//  Greps Ghost/**/*.g for a few queries and writes them in the Searchbar's own hit shape
//   ({path, line, name, glyph}; glyph ƒ def · % particle · ¶ mention — Searchbar.svelte:103-110), so a
//    Book can stand a result set that looks exactly like what the live search hands over, without the
//     Book needing disk or a warm Stemdex.  Re-run to refresh:  node scripts/vyto_search_sample.mjs
import { execSync } from 'node:child_process'
import fs from 'node:fs'

const QUERIES = ['Crew', 'Door', 'Heist']
const out = {}
for (const q of QUERIES) {
    const raw = execSync(`grep -rn --include=*.g ${JSON.stringify(q)} Ghost`, { encoding: 'utf8', maxBuffer: 1 << 26 })
    const hits = []
    for (const ln of raw.split('\n')) {
        const m = ln.match(/^([^:]+):(\d+):(.*)$/)
        if (!m) continue
        const [, path, line, text] = m
        const t = text.trim()
        const def = t.match(/^(?:async\s+)?([A-Za-z_]\w*)\([^)]*\):\s*$/)
        let glyph = '¶', name = t.length > 60 ? t.slice(0, 59) + '…' : t
        if (def && def[1].includes(q)) { glyph = 'ƒ'; name = def[1] }
        else if (new RegExp(`%${q}\\b|\\{\\s*${q}\\s*:`).test(t)) glyph = '%'
        hits.push({ path, line: +line, name, glyph })
    }
    hits.sort((a, b) => a.path < b.path ? -1 : a.path > b.path ? 1 : a.line - b.line)
    out[q] = hits
}
const body = `// GENERATED by scripts/vyto_search_sample.mjs — real greps of Ghost/**/*.g in the Searchbar's hit shape.\n`
    + `//  Do not hand-edit; re-run the script.\n`
    + `export type SampleHit = { path: string, line: number, name: string, glyph: string }\n`
    + `export const SEARCH_SAMPLE: Record<string, SampleHit[]> = ${JSON.stringify(out)}\n`
fs.writeFileSync('src/lib/O/vyto_search_sample.ts', body)
for (const q of QUERIES) console.log(q, out[q].length, 'hits', new Set(out[q].map(h => h.path)).size, 'files',
    Object.entries(out[q].reduce((a, h) => (a[h.glyph] = (a[h.glyph] || 0) + 1, a), {})).map(e => e.join('')).join(' '))
